#!/usr/bin/env bash
# Build an Ansible inventory from the currently-logged-in `oc` context.
# Writes ansible/inventory/clusters.yml — one host derived from `oc whoami`.
#
# This lets the demo run against the cluster you're logged into without
# requiring the workshop-style multi-cluster cluster_list.txt flow.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$REPO_ROOT/ansible/inventory/clusters.yml"

if ! command -v oc >/dev/null 2>&1; then
  echo "ERROR: oc not on PATH" >&2; exit 1
fi

API="$(oc whoami --show-server 2>/dev/null || true)"
TOKEN="$(oc whoami --show-token 2>/dev/null || true)"
USER="$(oc whoami 2>/dev/null || true)"

if [[ -z "$API" || -z "$TOKEN" ]]; then
  echo "ERROR: not logged into a cluster. Run 'oc login ...' first." >&2
  exit 1
fi

CLUSTER_NAME="$(echo "$API" | sed -E 's#https?://api\.([^.:]+).*#\1#' | sed 's/^$/current/')"

cat >"$OUT" <<EOF
# Generated by scripts/generate_inventory.sh from your active oc context.
# Cluster: $API  (user: $USER)
all:
  vars:
    ansible_connection: local
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
  hosts:
    ${CLUSTER_NAME}:
      k8s_host: "$API"
      k8s_api_key: "$TOKEN"
EOF

echo "wrote $OUT"
echo "  host: $CLUSTER_NAME"
echo "  api : $API"
echo "  user: $USER"
