- name: Set up workshop clusters
  hosts: all
  gather_facts: false
  module_defaults:
    group/kubernetes.core.k8s:
      host: "{{ k8s_host }}"
      api_key: "{{ k8s_api_key }}"
      validate_certs: "{{ validate_certs }}"
  roles:
    - workshop_cluster
